import languages from "Js/languages/index.js";

/**
 * List of translation for the account module
 */
const translations = {

  en: {
    tableDe0: 'O Times Multiplication Table',
    tableDe0Short: 'O Times Table',
    tableDe1: '1 Times Multiplication Table',
    tableDe1Short: '1 Times Table',
    tableDe2: '2 Times Multiplication Table',
    tableDe2Short: '2 Times Table',
    tableDe3: '3 Times Multiplication Table',
    tableDe3Short: '3 Times Table',
    tableDe4: '4 Times Multiplication Table',
    tableDe4Short: '4 Times Table',
    tableDe5: '5 Times Multiplication Table',
    tableDe5Short: '5 Times Table',
    tableDe5: '5 Times Multiplication Table',
    tableDe5Short: '5 Times Table',
    tableDe5: '5 Times Multiplication Table',
    tableDe5Short: '5 Times Table',
    tableDe5: '5 Times Multiplication Table',
    tableDe5Short: '5 Times Table',
    tableDe5: '5 Times Multiplication Table',
    tableDe5Short: '5 Times Table',
    tableDe6: '6 Times Multiplication Table',
    tableDe6Short: '6 Times Table',
    tableDe7: '7 Times Multiplication Table',
    tableDe7Short: '7 Times Table',
    tableDe8: '8 Times Multiplication Table',
    tableDe8Short: '8 Times Table',
    tableDe9: '9 Times Multiplication Table',
    tableDe9Short: '9 Times Table',
    tableDe10: '10 Times Multiplication Table',
    tableDe10Short: '10 Times Table',
    tableDe11: '11 Times Multiplication Table',
    tableDe11Short: '11 Times Table',
    tableDe12: '12 Times Multiplication Table',
    tableDe12Short: '12 Times Table',
    tableDe13: '13 Times Multiplication Table',
    tableDe13Short: '13 Times Table',
    tableDe14: '14 Times Multiplication Table',
    tableDe14Short: '14 Times Table',
    tableDe15: '15 Times Multiplication Table',
    tableDe15Short: '15 Times Table',
    tableDe16: '16 Times Multiplication Table',
    tableDe16Short: '16 Times Table',
    tableDe17: '17 Times Multiplication Table',
    tableDe17Short: '17 Times Table',
    tableDe18: '18 Times Multiplication Table',
    tableDe18Short: '18 Times Table',
    tableDe19: '19 Times Multiplication Table',
    tableDe19Short: '19 Times Table',
    tableDe20: '20 Times Multiplication Table',
    tableDe20Short: '20 Times Table',
  },



  fr: {
    tableDe0: 'Table de multiplication de 0',
    tableDe0Short: 'Table de 0',
    tableDe1: 'Table de multiplication de 1',
    tableDe1Short: 'Table de 1',
    tableDe2: 'Table de multiplication de 2',
    tableDe2Short: 'Table de 2',
    tableDe3: 'Table de multiplication de 3',
    tableDe3Short: 'Table de 3',
    tableDe4: 'Table de multiplication de 4',
    tableDe4Short: 'Table de 4',
    tableDe5: 'Table de multiplication de 5',
    tableDe5Short: 'Table de 5',
    tableDe6: 'Table de multiplication de 6',
    tableDe6Short: 'Table de 6',
    tableDe7: 'Table de multiplication de 7',
    tableDe7Short: 'Table de 7',
    tableDe8: 'Table de multiplication de 8',
    tableDe8Short: 'Table de 8',
    tableDe9: 'Table de multiplication de 9',
    tableDe9Short: 'Table de 9',
    tableDe10: 'Table de multiplication de 10',
    tableDe10Short: 'Table de 10',
    tableDe11: 'Table de multiplication de 11',
    tableDe11Short: 'Table de 11',
    tableDe12: 'Table de multiplication de 12',
    tableDe12Short: 'Table de 12',
    tableDe13: 'Table de multiplication de 13',
    tableDe13Short: 'Table de 13',
    tableDe14: 'Table de multiplication de 14',
    tableDe14Short: 'Table de 14',
    tableDe15: 'Table de multiplication de 15',
    tableDe15Short: 'Table de 15',
    tableDe16: 'Table de multiplication de 16',
    tableDe16Short: 'Table de 16',
    tableDe17: 'Table de multiplication de 17',
    tableDe17Short: 'Table de 17',
    tableDe18: 'Table de multiplication de 18',
    tableDe18Short: 'Table de 18',
    tableDe19: 'Table de multiplication de 19',
    tableDe19Short: 'Table de 19',
    tableDe20: 'Table de multiplication de 20',
    tableDe20Short: 'Table de 20',
  },
}

export default translations[languages.current()];

